// RootLayout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
// import { Analytics } from "./components/Analytics"; // Optional component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MindMate - Your Mental Health Companion",
  description: "AI-powered mental health support for your emotional well-being journey",
  keywords: "mental health, AI, journaling, mood tracking, emotional support",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body className="min-h-screen bg-gradient-to-b from-indigo-50 to-white dark:from-gray-900 dark:to-gray-800 transition-colors duration-500 antialiased">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          
          <main className="flex-grow w-full px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
          
          <footer className="mt-auto py-8 bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm border-t border-gray-200/50 dark:border-gray-800/50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex flex-col md:flex-row justify-between items-center">
                <div className="mb-4 md:mb-0">
                  <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-600 to-blue-500">MindMate</span>
                  <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Your AI-powered mental health companion</p>
                </div>
                
                <div className="flex space-x-6">
                  <a href="#" className="text-gray-500 hover:text-purple-600 dark:text-gray-400 dark:hover:text-purple-400 transition-colors">
                    Privacy
                  </a>
                  <a href="#" className="text-gray-500 hover:text-purple-600 dark:text-gray-400 dark:hover:text-purple-400 transition-colors">
                    Terms
                  </a>
                  <a href="#" className="text-gray-500 hover:text-purple-600 dark:text-gray-400 dark:hover:text-purple-400 transition-colors">
                    Contact
                  </a>
                </div>
              </div>
              
              <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-800">
                <p className="text-center text-sm text-gray-500 dark:text-gray-400">
                  © {new Date().getFullYear()} MindMate. All rights reserved.
                </p>
              </div>
            </div>
          </footer>
          
          {/* Optional Analytics component */}
          {/* <Analytics /> */}
        </div>
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className="bg-gray-50 text-gray-800 dark:bg-gray-900 dark:text-gray-100"
//       >
//         <Navbar/>
//        <main className="max-w-full mx-auto px-4 py-8">
//        {children}
//        </main>
//       </body>
//     </html>
//   );
// }
